fixed name overflow on sprites
BX-Coding/patch-ide pull request #122
Opened 2023-09-24 20:40 UTC by azure-kyuri

added name overflow on long sprite names (#94 )

2023-09-27 20:08 UTC, ElliotRoe requested changes
Looks good, just need to refactor the ternary and remove some code used for debugging

2023-09-27 20:08 UTC, ElliotRoe commented on src/components/SpritePane/SpriteCard.tsx
> +            {target?.sprite?.name.length > 13 ?
Would probably refactor this ternary into an if statement in the body of the component's function. Just so we don't have to repeat a bunch of JSX

2023-09-27 20:08 UTC, ElliotRoe commented on src/components/SpritePane/SpriteName.tsx
> +    }, [name])
Remove debug statements

2023-10-04 22:50 UTC, azure-kyuri commented
I refactored the ternary operator and also removed the debug statement in spriteName.tsx.

2024-02-18 14:42 UTC, ElliotRoe approved these changes

2024-02-18 14:42 UTC, merged